### ISSUE TITLE
Add +1 and session proposal workflow

### ISSUE THREAD

**Issue by drewww** [unhangout/unhangout#223]
Allow +1 voting for sessions before the session entry is open, so people can arbitrarily propose sessions, the audience can vote on them, and then organizers can delete sessions below a certain threshold BEFORE the event opens sessions. This lets us do   session workflow all within the tool rather than having to use other tools.

**Comment by srish** [comment]
The new "Participant Proposed Sessions" feature allows participants to propose sessions, vote on them and organizers to accept the ones that receive highest number of votes. Closing this for now.
