### ISSUE TITLE
Add facility for "flash" messages, use for login notification

### ISSUE THREAD

**Issue by yourcelf** [unhangout/unhangout#319]
A semi-transparent bar that can display informative messages, in particular for the case when someone logs in to an event page that hasn't started yet.

**Comment by thehunmonkgroup** [comment]
Just a note that #398 implements said functionality for its event template reloading functionality, it's pretty trivial to use the node module leveraged there for this as well.

**Comment by srish** [comment]
New design handles login notifications for event participants. Closing this issue for now.
