### ISSUE TITLE
Admin functions were disabling the UI controls. 

### ISSUE THREAD

**Issue by srish** [unhangout/unhangout#366]
Not sure what was the exact cause of this issue, but here are a couple of observations from the event: 

1) After opening the sessions, we could not longer type in the chat
2) After Katherine created the HOA, "Play-for-all" didn't work for her. But worked from my machine. 

Page reloading helped though.

**Comment by srish** [comment]
@kitsandkats did you experience this problem recently? If not, I am going to close this for now.

**Comment by kitsandkats** [comment]
I think it's fine to close this as well -- it still happens for me from
time to time, but I am not sure of a way to replicate the problem.
