### ISSUE TITLE
Hangout on Air not embedding properly in lobby

### ISSUE THREAD

**Issue by kitsandkats** [unhangout/unhangout#381]
When an admin uses the Create HOA button from the admin controls in the lobby, they are able to create a hangout on air, but the video does not embed in the lobby.

![screen shot 2014-11-10 at 11 06 01 am](https://cloud.githubusercontent.com/assets/6548760/4979444/0f3bd148-68f7-11e4-84ef-b5ab3e5feb1a.png)

**Comment by srish** [comment]
@kitsandkats did you experience this problem recently? If not, I am going to close this for now.

**Comment by kitsandkats** [comment]
I haven't had any reports of this recently and also haven't experienced it
myself. Seems fine to close it!
