### ISSUE TITLE
connected participants display on permalink page is vertical

### ISSUE THREAD

**Issue by kitsandkats** [unhangout/unhangout#407]
![screen shot 2015-06-30 at 11 01 59 am](https://cloud.githubusercontent.com/assets/6548760/8482199/025b036e-20b6-11e5-9588-7a7f2c13016e.png)

**Comment by srish** [comment]
fixed https://github.com/unhangout/unhangout/commit/4b09ffc7c3843742cf50cb445cc83a0ec9eb0eac
