### ISSUE TITLE
Redis error: redis end

### ISSUE THREAD

**Issue by dalareo** [unhangout/unhangout#478]
I am trying to dockerize Unhangout, in order to integrate it with [EduCaaS](https://educaas.github.io), an open platform for active learning programs.
I have created docker images and it is already published at Docker Hub (dalareo/unhangout-docker) but when I try to deploy it with docker-compose, using an image for Unhangout an another for Redis I get:

    redis error:
    redis end

Anybody?

**Comment by thehunmonkgroup** [comment]
The Redis service must be running, I'd start by checking that.

**Comment by dalareo** [comment]
It is an issue with Redis host name. I cannot set ENV variable from docker-compose and it gets default value ("localhost")
