### ISSUE TITLE
Sessions are "empty" with a red screen in the middle

### ISSUE THREAD

**Issue by dalareo** [unhangout/unhangout#479]
I have installed Unhangout on my server, available at mooc.fricolab.com:7777. I have created a dockerize installation, you can check image at https://hub.docker.com/r/dalareo/unhangout-docker/. Everything seems to be working nice but when I create sessions I just can find a big red rectangle in the middle, any help??

I am using Hangout  App Id of official Unhangout installation as it is mentiioned at https://github.com/unhangout/unhangout/blob/master/DEVELOPMENT.md

**Comment by thehunmonkgroup** [comment]
* Definitely recommend creating your own Hangout app, I'm not even sure the official Unhangout Hangout app will work properly on a custom install. It's not that hard to do, free, and will give you more control.
 * Check the server logs and the console log in the browser, I would expect you'd be able to spot something in there that will point to the source of the session creation issue.
 * Including a screenshot of the problem here may help in identifying the problem.

**Comment by yourcelf** [comment]
The red screen sounds like hangouts are in "mock" mode, which is used for testing without communicating to Google's servers.  To actually communicate with google's servers for hangouts, launch with `NODE_ENV=production`.

**Comment by dalareo** [comment]
My console says:


![captura de pantalla de 2016-07-14 10-43-16 png](https://cloud.githubusercontent.com/assets/919861/16833571/2804bd3e-49b0-11e6-9032-68d9a26d8323.png)

MOCK DATA Object { startTime: 1468485787445, users: Array[1], hangoutUrl: "http://mooc.fricolab.com:7777/test/…", appData: "sessionId:1:baseUrl:http%3A%2F%2Fmo…", isHoA: "false" } gadgetcontents:14:17
GADGET Unhangout Facilitator version 12 gadgetcontents:41:25
GADGET appData: sessionId:1:baseUrl:http%3A%2F%2Fmooc.fricolab.com%3A7777:sockKey:f19d08fd3954f06a01288b0ab1f6d7c761238dc83667676edd1dbf299cfe234c:userId:107358064645389651367 gadgetcontents:41:25
GADGET Session ID from appData: 1 gadgetcontents:41:25
GADGET BASE URL "http://mooc.fricolab.com:7777" gadgetcontents:41:25
GADGET FACILITATOR URL "http://mooc.fricolab.com:7777/facilitator/1/" gadgetcontents:41:25
GADGET URL ARGS Object { url: "http://mooc.fricolab.com:7777/test/…", id: "http://mooc.fricolab.com:7777/test/…", isHoA: "false", sockKey: "f19d08fd3954f06a01288b0ab1f6d7c7612…", userId: "107358064645389651367", youtubeId: "sXzK0AFpmcI" } gadgetcontents:41:25
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-2.0.0.js:4859:28
transport Array [ 1468485791221, 1 ] auth-ack undefined logger.js:33:17
transport Array [ 1468485791367, 2 ] join-ack undefined logger.js:33:17
FACILITATOR CDM inner set "http://mooc.fricolab.com:7777/test/hangout/1/" "http://mooc.fricolab.com:7777/test/hangout/1/-id" "http://mooc.fricolab.com:7777" logger.js:33:17
FACILITATOR Broadcasting new hangout URL "http://mooc.fricolab.com:7777/test/hangout/1/" logger.js:33:17
GADGET show video gadgetcontents:41:25
GADGET setDims undefined gadgetcontents:41:25
GADGET setDims Object { top: 0, left: 0, width: 574, height: 455 } gadgetcontents:41:25
GADGET outerCDM url-ack gadgetcontents:41:25
FACILITATOR CDM inner set "http://mooc.fricolab.com:7777/test/hangout/1/" "http://mooc.fricolab.com:7777/test/hangout/1/-id" "http://mooc.fricolab.com:7777" logger.js:33:17
GADGET outerCDM url-ack gadgetcontents:41:25
transport Array [ 1468485791557, 1 ] session/set-hangout-url-ack undefined logger.js:33:17
transport Array [ 1468485791558, 2 ] session/set-hangout-broadcast-id-err hoa not a hangout-on-air. logger.js:33:17
transport Object { type: "message", data: "{"type":"session/set-hangout-broadc…" } logger.js:33:17
Logger/prefixLogger/<() logger.js:33
Transport/this.sock.onmessage<() transport.js:60
REventTarget.prototype.dispatchEvent() sockjs-0.3.js:84
SockJS.prototype._dispatchMessage() sockjs-0.3.js:1025
SockJS.prototype._didMessage() sockjs-0.3.js:1083
SockJS.websocket/that.ws.onmessage() sockjs-0.3.js:1215

FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
transport Array [ 1468485792958, 1 ] session/set-connected-participants-ack undefined logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
GADGET setDims Object { top: 0, left: 0, width: 548, height: 277 } gadgetcontents:41:25
GADGET setDims Object { top: 0, left: 0, width: 561, height: 277 } gadgetcontents:41:25
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
Hangout got 'hideApp' call; app is now 'invisible'. mock-hangout-api.js:139:17
gapi.hangout.hideApp() mock-hangout-api.js:139
receiveMessage() gadgetcontents:198

FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17
FACILITATOR CDM inner participants: Object { participants: Array[1] } logger.js:33:17

**Comment by thehunmonkgroup** [comment]
Yep, as yourcelf said above, you're not starting the Unhangout node process in 'production' mode. However you're starting it, you'll want to make sure the environment has ```NODE_ENV=production``` set before you start.

For example, if you're starting it via command line using Bash, running the following before starting Unhangout should properly set up the environment:

```export NODE_ENV=production```

**Comment by dalareo** [comment]
Hi @thehunmonkgroup, I finally was able to set ENV variable in Dockerfile. Now I can connect Unhangout app but... CSS and JS are not working! I get this in console:

    facilitator.js pre-loaded..

and screen is empty. You can try at: http://mooc.fricolab.com:7777/event/event-url

**Comment by thehunmonkgroup** [comment]
The production configuration requires pre-compiled JS/CSS. Running ```node bin/compile-assets.js``` in the root Unhangout directory should accomplish that.

Also, if you're up for it, perhaps you can file a pull request to enhance INSTALLATTION.md with these tips we're providing. :)

**Comment by dalareo** [comment]
Done!
One more problem (I don't know if an issue to open another): I get an error when creating Hangout Air Session

    Error listing channel info.

**Comment by thehunmonkgroup** [comment]
There's already an open issue for the error you're seeing, #320
