### ISSUE TITLE
Show elapsed time for sessions that are live

### ISSUE THREAD

**Issue by drewww** [unhangout/unhangout#68]
Use the startTime field on the session model to drive this display.

Might need to do some tricky javascript to either re-render sessions periodically to get them to update their elapsed time, or use one of those timeSince libraries (for example: http://timeago.yarp.com/) to auto-update it based on the start time.

**Comment by srish** [comment]
@yourcelf @kitsandkats I am closing this issue for now, as we are not considering to implement it.
